### PR TITLE
add Chinese translation

### PR DESCRIPTION
**Pull request by LeoQuote**

### CODE REVIEW

**Comment by greengiraffe** [comment]
Hi @LeoQuote, thanks for your contribution!

Apparently, vercel builds are failing, possibly due to the EOL Node version. I'll have a look later on and update some dependencies in order to get it running again.

**Comment by LeoQuote** [comment]
@greengiraffe yeah, could be, but it could work with nodejs 16 in my pc, maybe we should upgrade node-sass if possible, or delete it since it's [deprecated](https://sass-lang.com/blog/libsass-is-deprecated)

**Comment by LeoQuote** [comment]
replacing node-sass with sass , and change compile engine to node 18, will raise error:
```
 ERROR  Failed to compile with 1 error                                                                                                                                                                                          00:55:03

 error  in ./src/components/ScoringTable.vue?vue&type=style&index=0&id=03a4da22&scoped=true&lang=scss&

Syntax Error: SassError: expected selector.
    ╷
311 │ }
    │  ^
    ╵
  src\components\ScoringTable.vue 311:2  root stylesheet


 @ ./node_modules/vue-style-loader??ref--8-oneOf-1-0!./node_modules/@vue/cli-service/node_modules/css-loader/dist/cjs.js??ref--8-oneOf-1-1!./node_modules/@vue/cli-service/node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node
_modules/postcss-loader/src??ref--8-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js??ref--8-oneOf-1-3!./node_modules/style-resources-loader/lib??ref--8-oneOf-1-4!./node_modules/@vue/cli-service/node_modules/cache-loader/dist/cjs.js
??ref--0-0!./node_modules/@vue/cli-service/node_modules/vue-loader/lib??vue-loader-options!./src/components/ScoringTable.vue?vue&type=style&index=0&id=03a4da22&scoped=true&lang=scss& 4:14-660 14:3-18:5 15:22-668
 @ ./src/components/ScoringTable.vue?vue&type=style&index=0&id=03a4da22&scoped=true&lang=scss&
 @ ./src/components/ScoringTable.vue
 @ ./node_modules/@vue/cli-plugin-babel/node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/@vue/cli-plugin-babel/node_modules/babel-loader/lib!./node_modules/@vue/cli-service/node_modules/cache-loader/dist/cjs.js??ref--
0-0!./node_modules/@vue/cli-service/node_modules/vue-loader/lib??vue-loader-options!./src/views/Scoresheet.vue?vue&type=script&lang=js&
 @ ./src/views/Scoresheet.vue?vue&type=script&lang=js&
 @ ./src/views/Scoresheet.vue
 @ ./node_modules/@vue/cli-plugin-babel/node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/@vue/cli-plugin-babel/node_modules/babel-loader/lib!./node_modules/@vue/cli-service/node_modules/cache-loader/dist/cjs.js??ref--
0-0!./node_modules/@vue/cli-service/node_modules/vue-loader/lib??vue-loader-options!./src/App.vue?vue&type=script&lang=js&
 @ ./src/App.vue?vue&type=script&lang=js&
 @ ./src/App.vue
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.1.10:8080&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js
```

if node 18 is selected, there would be another error complaining that `@achrinza/node-ipc` does not support node 18 , which cannot be upgraded because @vue/cli-service needs it.

IMHO, we should start over this whole project 🤦‍

**Comment by greengiraffe** [comment]
@LeoQuote I finally upgraded the project to Vue 3 and Vite! 🚀 I'd be happy to merge your MR after you've adapted it to the latest version, the necessary changes should be simple.

**Comment by LeoQuote** [comment]
@greengiraffe wow，thanks for your work，I’ll do that ASAP

**Comment by LeoQuote** [comment]
@greengiraffe I think it's good to go

**Comment by greengiraffe** [comment]
@LeoQuote Sorry for the long wait, I've finally managed to merge this. I also updated the select style to match the rest of the UI and while I was at it I gave the whole app a small UI refresh, I hope you like it :)

Thanks for the contribution and enjoy playing Wingspan!

**Pull request merged**
